### ISSUE TITLE
No longer working after supplemental OS updates?

### ISSUE THREAD

**Issue by grantbarrett** [hbwhite/Clutch#5] opened 2019-09-25 20:00 UTC
Sorry for my inexpert explanation, but it looks like Clutch is doing something to the Transmission preferences so that the binding no longer works. After the Linux torrents stopped seeding or downloading, I went through a few steps to figure out why. If I create a new user account, which would then have virgin Transmission, Clutch and VPN settings, then everything is alright at first. The VPN works and passes traffic as it should. Then if I launch Transmission it can download torrents as it should through the VPN, no problem. Then enabling Clutch and binding it to the VPN interface works, too — but only the first time. After I unbind Clutch, it never works again, even if it's simply Transmission attempting to work with the VPN without binding. I don't have a lot of time to troubleshoot this more right now but I saw one other person talking about it on Reddit so I thought it worth bringing here where it might get some relevant attention. I'm not sure what changed but I assume it was one of the recent macOS supplemental updates because all the other software involved has not changed as far as I know.

**Comment by hbwhite** [comment] 2019-09-25 20:10
Hi Grant,

This is the first time I've heard of this issue. Can you please send me these files so I can investigate it further?

/Users/your-user-name/Library/Preferences/org.m0k.transmission.plist
/Users/your-user-name/Library/Preferences/8TSRGQJRTM.group.com.rcx.clutch.plist

Also, please send me the link to the Reddit thread. Maybe this app is more popular than I realized.

I will get back to you ASAP as soon as I receive these files.

Thanks,

Harrison

**Comment by hbwhite** [comment] 2019-09-25 20:28
Also, please make sure that you're using the latest version of Clutch (v1.3), as some important networking issues were fixed in the last few releases. You can download it from the main GitHub page or from the "Releases" tab.

**Comment by grantbarrett** [comment] 2019-09-26 23:45
Thanks for the prompt response. I am using the latest version of Clutch and downloaded a new copy, anyway, in case something was amiss on my end.

The Reddit thread is here: https://www.reddit.com/r/VPNTorrents/comments/cjjpg1/ivacy_kill_switch_for_mac/ It's from about a month ago, which is, incidentally, about when my trouble started and when macOS 10.4.6 Supplemental Update #2 was released, I believe, though perhaps that's a coincidence.

I am attaching the two most recent versions of the preference files, both created after a clean reinstall of Clutch and Transmission in a virgin user account. One set are from when it the setup was working and another set are from a few minutes later, when the setup stopped working after unbinding and rebinding. 

[Clutch-Transmission-prefs.zip](https://github.com/hbwhite/Clutch/files/3660264/Clutch-Transmission-prefs.zip)

As for the popularity of this app, I don't know anything about, but it sure solves a problem for me. I was using a number of kludgy solutions before and the simplicity of this is perfect. If Clutch can help me avoid switching over from the ease and elegance of Transmission to some nightmarish torrent app like Vuze that has this sort of function built-in, then great.

**Comment by grantbarrett** [comment] 2019-09-26 23:49
Incidentally, both the Reddit poster and I are using Ivacy for our VPN.

**Comment by hbwhite** [comment] 2019-09-27 00:15
Hi Grant, I'm looking at it now. On the same user account you used to test it, can you try unbinding it and sending me the preferences file again? You mentioned that it didn't work even after unbinding once you bound it the first time.

Thanks,

Harrison

**Comment by hbwhite** [comment] 2019-09-27 00:15
* Both preferences files, I mean.

**Comment by hbwhite** [comment] 2019-09-27 01:27
Hello again, I have a possible fix but I need your feedback to see if the problem is what I think it is.

Open Terminal, type "ifconfig" and press Enter, and copy and paste the output here. If you want, you can censor out the lines that start with "ether" which contain your unique interface addresses. I'm looking for the interface names and IPv6 addresses.

What I think is happening is that you have multiple interfaces under the name "utun0" and Clutch is binding to the first one, even though it is a link-local address that doesn't actually run through your VPN, but rather just sends normal traffic (which happens to flow through your VPN if it is running). I can change the code to ignore these so it binds to the right one, but I need to make sure that that's the actual issue.

Thanks,

Harrison

**Comment by grantbarrett** [comment] 2019-09-27 14:36
Here you go. 

In my original user account, I have tried selecting utun1 and utun0 to no effect. 

This morning I notice in my test user account that selecting utun0 in Clutch works but because it's a IPV6 address I am not sure the data is passing through the VPN. Selecting utun1 seems to work at first — peers are indicated — but no data passes; Clutch shows that has the IP address indicated in the VPN (Ivacy) interface in the Network control panel. 

[ifconfig-files.zip](https://github.com/hbwhite/Clutch/files/3663150/ifconfig-files.zip)

I am including the ifconfig files from both accounts here.

PS: On second go-through on the test account with a more popular torrent, I see that it works fin with utun1 in the test account. WTF. So. Maybe I am wasting your time. :/. Maybe I'll just migrate everything over from the other account.

**Comment by grantbarrett** [comment] 2019-09-28 23:21
Okay, I've messed with it some more and I can see a little clearer why it appears to be intermittent. In recreating the circumstances mentioned in my PS above, if I start a torrent in the clear and let it find a few peers, then turn on Ivacy and then use Clutch to bind Transmission to utun0, then the torrent will work 100% of the time. However, if I first start Ivacy, then bind Transmission with Clutch, then start the Torrent, the torrent fails to do anything 100% of the time.  I have recreated this now a dozen times.

**Comment by hbwhite** [comment] 2019-09-28 23:23
Thanks for researching the problem further. I’ve been busy with work but I’ll look at it tonight. This is very helpful.

**Comment by grantbarrett** [comment] 2019-09-28 23:25
Thank you. I appreciate all your attention to this. I know it can't be the most important thing you have going!

**Comment by rr0ss0rr** [comment] 2019-09-28 23:48
Does Transmission work If you restart Transmission after Clutch modifies the bind address?

**Comment by hbwhite** [comment] 2019-09-29 03:29
Hi Grant, it looks like you may just be binding to the wrong interface.

Based on your ifconfig output, it looks like you should be binding to utun1, which is an IPv4 address, NOT utun0. The original preference files you sent me were for binding to utun0 with a link-local IPv6 address.

Can you repeat your above experiment ("first start Ivacy, then bind Transmission with Clutch, then start the Torrent, the torrent fails to do anything") but when binding to utun1?

**Comment by grantbarrett** [comment] 2019-09-29 14:25
Harrison, in the past it has literally never worked if I bound to utun1. Not once, not ever. It sometimes worked for utun1, as explained above. That could have been an Ivacy problem, and not a Clutch problem (or a Transmission problem — it is a bit long in the tooth and seems somewhat neglected). However, I have done yet another virgin user account, reinstalled all the involved applications, used their default settings where possible, tried only the mostly popular Linux release torrents, and it now seems to work for both utun0 and utun1. Isn't utun0 simply the IPv6 address for the same IPv4 address at utun1?

Transmission *does* work if I restart Transmission after Clutch modifies the bind address.

**Comment by grantbarrett** [comment] 2019-09-29 14:30
Anyway, I want to thank you for your time. I feel like I have a semi-stable solution here and am willing to move forward without wasting any more of your time. Clearly, something was wrong here and I'm not sure it was Clutch. If you have a tip jar somewhere, please let me know.

**Comment by hbwhite** [comment] 2019-09-29 16:12
Hi Grant, please don’t worry about the time it takes. I want this app to be as stable as possible. If you’re willing to take the time to help me debug this, I’m more than happy to take the time to fix it.

Now, you said “Transmission does work if I restart Transmission after Clutch modifies the bind address.” When you click “bind,” Clutch should automatically quit and restart Transmission. Does this happen?

And if you manually quit and restart Transmission, it ALWAYS works, correct?

I’m wondering if it’s just a race condition, where Clutch can’t write Transmission’s preferences fast enough, and it restarts before Clutch is finished. Are you using a mechanical hard drive by chance? (Not an SSD.)

Most VPNs let you regenerate the VPN login. Would you mind generating a new login and password and letting me borrow your Ivacy account to see if I can replicate this? You can email me at hbwhite (at) protonmail.com. And are you using an Ivacy client app or a third-party app to connect?

Thank you for taking the time to help debug this issue. Users like you keep the app working properly, and I appreciate it!

**Closed** 2020-02-02 23:41 UTC
